"""The Appium module's domain: entities, boundary DTOs and ports.

Imports nothing from ``infrastructure``, ``application`` or ``presentation``, and
nothing from a third-party I/O library. It is importable on a host with no
Appium, no Node and no Android SDK, which the architecture test asserts.
"""

from .errors import (
    AppiumModuleError,
    AppNotFound,
    BackendFailure,
    BackendUnavailable,
    DeviceNotFound,
    DriverInstallFailed,
    DriverNotInstalled,
    ElementNotFound,
    InteractionFailed,
    InvalidCoordinates,
    InvalidDeviceId,
    InvalidKeyName,
    InvalidLocator,
    InvalidScroll,
    ScreenshotFailed,
    ServerStartFailed,
    ServerUnreachable,
    SessionExpired,
    SessionNotFound,
    SessionStartFailed,
)
from .models import (
    FOCUSED_STRATEGY,
    LOCATOR_STRATEGIES,
    SCROLL_DIRECTIONS,
    AppiumSession,
    CheckEnvironmentRequest,
    ElementInteractionResult,
    EndSessionRequest,
    EndSessionResult,
    EnvironmentStatus,
    GetPageSourceRequest,
    InstallDriverRequest,
    InstallDriverResult,
    InteractionResult,
    ListSessionsRequest,
    ListSessionsResult,
    PageSourceResult,
    PressKeyRequest,
    ScreenshotResult,
    ScrollRequest,
    StartSessionRequest,
    StartSessionResult,
    SwipeRequest,
    TakeScreenshotRequest,
    TapElementRequest,
    TapRequest,
    ToolStatus,
    TypeTextRequest,
)
from .ports import AppiumEnvironment, DeviceInteraction, ScreenInspector, SessionLifecycle

__all__ = [
    # ports
    "AppiumEnvironment",
    "SessionLifecycle",
    "ScreenInspector",
    "DeviceInteraction",
    # requests
    "CheckEnvironmentRequest",
    "InstallDriverRequest",
    "StartSessionRequest",
    "EndSessionRequest",
    "ListSessionsRequest",
    "TakeScreenshotRequest",
    "GetPageSourceRequest",
    "TapRequest",
    "TapElementRequest",
    "SwipeRequest",
    "ScrollRequest",
    "TypeTextRequest",
    "PressKeyRequest",
    # results and value objects
    "ToolStatus",
    "EnvironmentStatus",
    "InstallDriverResult",
    "AppiumSession",
    "StartSessionResult",
    "EndSessionResult",
    "ListSessionsResult",
    "ScreenshotResult",
    "PageSourceResult",
    "InteractionResult",
    "ElementInteractionResult",
    # vocabulary
    "FOCUSED_STRATEGY",
    "LOCATOR_STRATEGIES",
    "SCROLL_DIRECTIONS",
    # errors
    "AppiumModuleError",
    "BackendUnavailable",
    "BackendFailure",
    "DriverNotInstalled",
    "DriverInstallFailed",
    "ServerStartFailed",
    "ServerUnreachable",
    "InvalidDeviceId",
    "InvalidLocator",
    "InvalidCoordinates",
    "InvalidKeyName",
    "InvalidScroll",
    "AppNotFound",
    "SessionNotFound",
    "SessionStartFailed",
    "SessionExpired",
    "DeviceNotFound",
    "ElementNotFound",
    "InteractionFailed",
    "ScreenshotFailed",
]
